Front top tag
sakaba-project/sakaba-front pull request #16
Opened 2020-07-01 10:29 UTC by naoi217

おねがいします

2020-07-05 14:26 UTC, shamisonn requested changes
> HTML、CSSの書き方がパッと見きもくないか。

scoped cssを使っていてめっちゃ見やすかったです！Vueすき！！！いいっすね！

> UI図：https://drive.google.com/file/d/1NWRm-PIzBgNPBOBcwp4WazugJFkZsbb9/view?usp=sharing
を元に表示崩れや不備がないかチェック

こっちの点でちょっとだけ細かいところ書いてみました！
提案程度に見てもらって、もとのほうがいいなーってなったらその旨コメントください！

2020-07-05 14:26 UTC, shamisonn commented on src/components/Tag.vue
> +    <a href="#" class="btn-icon"><p class="tag-name"># {{ tagName }}</p></a>
下記でもいい気がしたけど何か理由ってあったりする？
```suggestion
    <a href="#" class="btn-icon"><p class="tag-name">#{{ tagName }}</p></a>
```

2020-07-05 14:26 UTC, shamisonn commented on src/components/Tag.vue
> +}
ちょっと上下の空白がきになったりしたので、こんな感じにしても良さそうにみえました！
```suggestion
.tag-name {
  font-size: 0.5em;
  padding: 0.5em;
  margin: 0;
}
```

2020-07-05 14:26 UTC, shamisonn commented on src/components/Top.vue
> +    <!-- TODO: v-forにする。href動的に生成する。 -->
👍

2020-07-11 07:01 UTC, naoi217 commented
再レビューをお願いしまああす

2020-07-11 09:50 UTC, shamisonn commented
@naoi217 LGTM!

2020-07-11 09:50 UTC, shamisonn approved these changes

2020-07-11 09:50 UTC, merged